### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by cmdte** [parandea17/FaceDetection#2]
It seems the implementation doesn't work. It classifies almost all non-faces correctly but all faces incorrectly (False Negative Rate - 98%).

**Comment by aparande** [comment]
How many weak classifiers are you using? With 200 weak classifiers (in the `200.pkl` file), I had a False Negative Rate of 78%. Using 50 weak classifiers (in the `50.pkl` file), I had a False Negative Rate of 65%. While both of those are not great, they are very far from 98%.

In general, Viola-Jones is heavily adverse to False Positives and doesn't care as much about False Negatives. That is why with more weak classifiers, we get higher False Negative rates. There is a trade-off between allowing False Positives and False Negatives, so the number of weak classifiers should be based on what the application will be. A higher-resolution data-set would also be helpful in solving this issue since the CBCL dataset has very low-dimensional photos which can be hard to classify with.

**Comment by cmdte** [comment]
![image](https://user-images.githubusercontent.com/42968789/57734449-92261d00-76aa-11e9-8695-6a3973d44a9b.png)
I'm using your cascade.pkl.

**Comment by cmdte** [comment]
Unfortunately, using a higher-resolution data-set (100x40 in my case) leads to memory error. Anyway, thank you for explanation.

**Comment by aparande** [comment]
The Attentional Cascade optimizes against False Negatives even more than regular Viola-Jones which explains why its False Negative Rate is much higher. When Viola-Jones was widely used in industry, there must have been other optimizations which helped bring that False Negative Rate down.
